import type { Metadata } from 'next';
import './globals.css';
import { Web3Provider } from './context/Web3Context';
import { UserProvider } from './context/UserContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Web3Provider>
          <UserProvider>
            {children}
          </UserProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
