import type { Metadata } from "next"
import "./globals.css"
import MagicProvider from "./context/MagicProvider"
import { UserProvider } from "./context/UserContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MagicProvider>
          <UserProvider>{children}</UserProvider>
        </MagicProvider>
      </body>
    </html>
  )
}
